### ISSUE TITLE
Honing the presentation

### ISSUE THREAD

**Issue by boblangley** [danielmarbach/service-fabric-webinar#3]
Webinar Outline:

- [ ] Introduction [1 minute]
- [ ] Scenario [1 minute]
- [ ] Current State: RPC - Quick Demo of running app [3 minutes]
      - [ ] Code - Front controller, back controller
      - [ ] Submit an order or 3
- [ ] Sophia raises concern about temporal coupling [1 minute]
      1. Latency / User Experience
- [ ] Benefits of Messaging [5 minutes]
   - [ ] Retries - longer
   - [ ] Transactions
   - [ ] Throttling
   - [ ] Extensibility - Pub/Sub
   - [ ] Auditing
- [ ] NServiceBus - team didn't want to build it themselves, use a battle-tested professional framework with world-class support. [3 minutes]
- [ ] Convert Front/Back to Queues [10 minutes]
   - [ ] Orders demo
   - [ ] New Front controller action
   - [ ] Handler
   - [ ] Saga
   - [ ] Endpoint communication listener
   - [ ] Show Rabbit Queues
   - [ ] Service Insight
- [ ] Scaling your application further: [3 minutes]
   - [ ] Move state closer to the front end
   - [ ] Partition our data
   - [ ] Reduce latency on storage - In-memory cache with persistence
         1. Reliable Collections
- [ ] Convert to stateful services [10 minutes]
   - [ ] Handler
   - [ ] Saga
   - [ ] ServiceFabric Persister
        1. Store saga data to reliable collections
         2. Share reliable collection transaction with saga data - no need for DTC
   - [ ] Partition affine routing
         1. RSD - quick diagram
         2. SSD - quick diagram
         3. Show Rabbit Queues - instance partition queues
- [ ] Outro [1 minute]

**Comment by danielmarbach** [comment]
Closing this since the slides and demos are done and contain all the points outlined above
